language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=master

matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO=master

install:
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
