language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

sudo: false

env:
  - DJANGO=3.2
  - DJANGO=4.0
  - DJANGO=master

matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO=master

install:
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
